### ISSUE TITLE
Add source code to repo

### ISSUE THREAD

**Issue by reisir** [ghostseven/Starfield-UI#1]
repo with no source code kinda sus :raised_eyebrow:

**Comment by modkavartini** [comment]
fr

**Comment by ghostseven** [comment]
I agree, it was quickly uploaded after I created the project. Rainmeter files allow you to view the source etc but I suppose it could be malicious.  If I get a chance I will break the files out and upload but not high priority at the moment. My apologies for that.

**Comment by ghostseven** [comment]
Acttually looking at this it was easier than I thought, so further apologies.  The source files will not insall plugins as this is just a dump of the relevant Rainmeter folder. But you can see all the code and LUA etc and use the source to go forward without using the package. I hope that is ok.

**Comment by modkavartini** [comment]
also, i suggest you add the `rainmeter` or [other valid tags](https://github.com/meters-on-demand/mond-api/wiki/Adding-skins#required-steps) to your repo so that it gets added to the rainmeter package manager, [MonD](https://github.com/meters-on-demand/cli), you may also perform the [optional steps](https://github.com/meters-on-demand/mond-api/wiki/Adding-skins#optional-steps).

great suite btw, love the design :3
